require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - rialto-etl.gemspec

RSpec/AnyInstance:
  Exclude:
  - spec/extractors/stanford_organizations_spec.rb
  - spec/extractors/stanford_researchers_spec.rb
  - spec/readers/ndjson_reader_spec.rb
  - spec/readers/sparql_statement_reader_spec.rb
  - spec/transformers/people_spec.rb
  - spec/writers/sparql_writer_spec.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/IteratedExpectation:
  Exclude:
    - spec/readers/*.rb

RSpec/DescribeClass:
  Exclude:
    - spec/transform/*.rb


RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/SubjectStub:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - lib/rialto/etl/configs/*.rb
