language: ruby
sudo: false
dist: trusty
cache:
  bundler: true
rvm:
  - 2.5.1
git:
  submodules: false
before_install: gem install bundler
bundler_args: --without debug

env:
  global:
    - CC_TEST_REPORTER_ID=ca075549329bb91a4e26b08cbd823b834e9f34ac89fa7ac5d7f9f6ba3c042c3f
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
