# These settings can also be provided as environment variables, in the form, e.g.:
#    SETTINGS__CAP__API_KEY=foobar
#
# The mapping is described in `./lib/rialto/etl/configuration.rb`.

cap:
  api_key: 'dummyvalue'

wos:
  api_key: 'evendumbervalue'
  # From WoS API docs: https://developer.clarivate.com/swagger-ui/?url=/apis/wos/swagger
  #
  # Load time span (otherwise described as symbolic time span) defines a range
  # of load dates. The load date is the date a record was added to the database.
  # If load date is specified, the publishTimeSpan parameter must be omitted. If
  # both publishTimeSpan and loadTimeSpan are omitted, the maximum publication
  # date will be inferred from the editions data. Any of D/W/M/Y prefixed with a
  # number where D-Day, M-Month, W-Week, Y-Year allowed. Acceptable value range
  # for Day(0-6), Week(1-52), Month(1-12) and Year(0-10), ex: 5D,30W,10M,8Y
  load_timespan: '8W'

sera:
  clientid: placeholderid
  secret: sekret1!
  token_url: https://aswsuat.stanford.edu/api/oauth/token
  service_url: https://aswsuat.stanford.edu

sparql_writer:
  update_url: http://127.0.0.1:9999/blazegraph/namespace/kb/sparql

entity_resolver:
  url: http://127.0.0.1:3001/
  api_key: abc123
